
name: AUTOMATION - TEST - CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
          
      - name: Install dependencies
        run: |
          echo "Installing dependencies... 📦"
          npm install --no-audit --no-fund

      - name: Start web app
        run: |
          echo "Starting web app... 🚀"
          npm run dev & npm run test:headless

      - name: Stop web app
        if: success() || failure()
        run: |
          echo "Stopping web app... 🛑"
          pkill -f "npm run dev"
  
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/law-finder-frontend:latest
  
  deploy-to-do:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: DigitalOcean App Deployment Action
        uses: rdarida/digitalocean-app-deployment-action@v1.0.2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          appId: ${{ secrets.DIGITALOCEAN_APPID }}
      